export const PERMISSIONS = {
  // Menu
  MENU_DASHBOARD:  'menu.dashboard',
  MENU_RECRUITING: 'menu.recruiting',
  MENU_ROADSHOW:   'menu.roadshow',
  MENU_INVENTORY:  'menu.inventory',
  MENU_FINANCE:    'menu.finance',
  MENU_APPROVALS:  'menu.approvals',
  MENU_AUDIT:      'menu.audit',
  MENU_ADMIN:      'menu.admin',

  // Action
  CANDIDATE_READ:   'candidate.read',
  CANDIDATE_WRITE:  'candidate.write',
  ITINERARY_READ:           'itinerary.read',
  ITINERARY_WRITE:          'itinerary.write',
  ITINERARY_TEMPLATE_MANAGE:'itinerary.template.manage',
  VENUE_READ:               'venue.read',
  VENUE_WRITE:              'venue.write',
  EVENT_READ:               'event.read',
  EVENT_WRITE:              'event.write',
  ORDER_READ:               'order.read',
  ORDER_WRITE:              'order.write',
  PAYMENT_COLLECT:          'payment.collect',
  REFUND_ISSUE:             'refund.issue',
  APPROVAL_SUBMIT:          'approval.submit',
  DATA_INGEST:              'data.ingest',
  WORKFLOW_DEFINE:          'workflow.define',
  WORKFLOW_VIEW:            'workflow.view',
  VENDOR_READ:              'vendor.read',
  VENDOR_WRITE:             'vendor.write',
  VENDOR_BANKING_READ:      'vendor.banking.read',
  VENDOR_BANKING_WRITE:     'vendor.banking.write',
  ROADSHOW_READ:    'roadshow.read',
  ROADSHOW_WRITE:   'roadshow.write',
  INVENTORY_READ:   'inventory.read',
  INVENTORY_WRITE:  'inventory.write',
  INVENTORY_ISSUE:  'inventory.issue',
  FINANCE_READ:     'finance.read',
  FINANCE_WRITE:    'finance.write',
  APPROVAL_APPROVE: 'approval.approve',
  APPROVAL_REJECT:  'approval.reject',
  AUDIT_READ:       'audit.read',
  USER_MANAGE:      'user.manage',
  ROLE_MANAGE:      'role.manage',

  // Data
  DATA_CITY_ALL:      'data.city.all',
  DATA_CITY_ASSIGNED: 'data.city.assigned',
  DATA_FINANCE_ALL:   'data.finance.all'
};
